### This makefile shows how to use the GPU accelerated libdirac 
CC=gcc
CFLAGS= -Wall -g #-pg
CLIBS= -lm -lpthread

# need BLAS/LAPACK, preferably openblas
LAPACK=-lopenblas -lgfortran -lpthread
LAPACK_DIR=/usr/local/OpenBLAS/lib/

# path to include Dirac.h
INCLUDES= -I../../src/lib/Dirac/
# path to LAPACK and libdirac.a
LIBPATH=-L$(LAPACK_DIR) -L../../build/dist/lib/
# Dirac (Note: when linking, this should be first lib)
LDIRAC=-ldirac

# CUDA flags
CUDAINC=-I/usr/local/cuda/include
CUDALIB=-L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcusolver

#### glib
GLIBI=-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include/ -I/usr/lib64/glib-2.0/include
GLIBL=-lglib-2.0

OBJECTSSTOCHASTIC=demo_stochastic_cuda.o
default:demo_stochastic_cuda
demo_stochastic_cuda.o:demo_stochastic_cuda.c
	$(CC) $(CFLAGS) $(INCLUDES) $(GLIBI) $(CUDAINC) -c $<
demo_stochastic_cuda: $(OBJECTSSTOCHASTIC)
	$(CC)  $(CFLAGS) $(INCLUDES) $(GLIBI)  -o $@ $(OBJECTSSTOCHASTIC) $(LDIRAC) $(CUDALIB) $(CLIBS) $(LIBPATH) $(LAPACK)
