OUTPUT=
CXX=/software/users/lofareor/sarod/openmpi/bin/mpic++
CXXFLAGS=-O3 -Wall -g -DHAVE_CUDA
CASA_LIBDIR=/software/users/lofarsoft/software/local/casacore/lib
CASA_INCDIR=/software/users/lofarsoft/software/local/casacore/include/casacore
CASA_LIBS=-lcasa_casa -lcasa_tables -lcasa_measures -lcasa_ms -lcfitsio -lhdf5 -lcasa_scimath_f -lcasa_scimath
#LAPACK=-llapack -lblas
#LAPACK=-lgoto2 -lgfortran -lpthread
LAPACK=-lopenblas -lgfortran -lpthread
LAPACK_DIR=-L/home/users/yatawatta/extern/lib -L/software/users/lofarsoft/software/local/lib64 -L/usr/lib64 -L.

CUDAINC=-I/software/users/lofarsoft/software/local/cuda/include
CUDALIB=-L/software/users/lofarsoft/software/local/cuda/lib64 -lcuda -lcudart

CULA_BIN_PATH_64=/software/users/lofarsoft/software/local/cula/bin64
CULA_ROOT=/software/users/lofarsoft/software/local/cula
CULA_LIB_PATH_64=/software/users/lofarsoft/software/local/cula/lib64
CULA_INC_PATH=/software/users/lofarsoft/software/local/cula/include
CULALIB=-lcula_core -lcula_lapack -lcublas

LDFLAGS=-Wl,--rpath,/home/users/yatawatta/extern/lib

# with multithread FFTW
MY_LIBS=-lm -lsagecal
INCLUDES=-I. -I./lib -I$(CASA_INCDIR) -I/usr/include -I${CULA_INC_PATH} $(CUDAINC)
LIBPATH=$(LAPACK_DIR) -L$(CASA_LIBDIR)  -L./lib -L${CULA_LIB_PATH_64}

#### glib
GLIBI=-I/software/users/lofarsoft/software/local/include/glib-2.0 -I/software/users/lofarsoft/software/local/lib/glib-2.0/include/
GLIBL=-lglib-2.0 -L/software/users/lofarsoft/software/local/lib

OBJECTS=main.o data.o sagecal_master.o sagecal_slave.o
default:sagecal-mpi
main.o:main.cpp proto.h
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(GLIBI) -c $<
data.o:data.cpp data.h
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(GLIBI) -c $<
sagecal_master.o:sagecal_master.cpp proto.h
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(GLIBI) -c $<
sagecal_slave.o:sagecal_slave.cpp proto.h
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(GLIBI) -c $<
sagecal-mpi:$(OBJECTS) ./lib/libsagecal.a
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(INCLUDES) $(GLIBI) $(LIBPATH)  -o $@  $(OBJECTS) $(MY_LIBS) $(CASA_LIBS)  $(GLIBL) $(LAPACK) $(CUDALIB) $(CULALIB)
clean:
	rm *.o *.tmp *.fits
